### ISSUE TITLE
Not able to use the layout--right class.

### ISSUE THREAD

**Issue by Aanchal25** [PredixDev/px-layout-design#1]
sass file is not getting compiled,and there is no css folder,hence not able to use the layout--right class.

**Comment by nonmetalhail** [comment]
Where are you trying to compile it?

**Comment by Aanchal25** [comment]
I am using predix-seed.Do you have any css folder in px-layout-design?Are you able to use (layout--right,layout--left etc)  classes of px-layout-design.

**Comment by ek** [comment]
Hi Anachal25, can you please post a gist or point us to your repo so that we can reproduce?

**Comment by nonmetalhail** [comment]
So if you are looking for css in the design repos, then no, there is none. The design repos only contain Sass which will get compiled in the components where they are needed. If you want to use the layout classes, import it into the Sass in the component, in your case predix-seed, use the proper import flags, and then you'll have access. If this doesnt answer you question, then please do post more info so we can reproduce.

**Comment by randyaskin** [comment]
Closing due to lack of response. Let us know if you are still having issues.
