### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by szalonna** [PredixDev/px-layout-design#2]
Hello,
I installed px-layout-design with Bower into an empty project and when I try to build the following SCSS file, I get an error.

My SCSS:

```
$inuit-enable-layout--tiny: true;
$inuit-enable-layout--small: true;
$inuit-enable-layout--large: true;
$inuit-enable-layout--huge: true;
$inuit-enable-layout--flush: true;
$inuit-enable-layout--rev: true;
$inuit-enable-layout--middle: true;
$inuit-enable-layout--bottom: true;
$inuit-enable-layout--full: true;
$inuit-enable-layout--right: true;
$inuit-enable-layout--center: true;
$inuit-enable-layout__item--full: true;
$inuit-enable-layout__item--center: true;
$inuit-enable-layout__item--bottom: true;

@import "px-layout-design/_objects.layout.scss";
```

Error:

```
Error: File to import not found or unreadable: inuit-responsive-tools/_tools.responsive.scss.
       Load path: /bower_components
        on line 18 of /bower_components/px-layout-design/_objects.layout.scss
        from line 27 of style.scss
  Use --trace for backtrace.
```

SCSS compiler is configured to resolve imports from bower_components folder.

Thanks!

**Comment by adrian110288** [comment]
@szalonna https://www.npmjs.com/package/inuit-responsive-tools

**Comment by randyaskin** [comment]
Sorry for the very delayed response. @adrian110288 's link works for grabbing it directly, but inuit-responsive-tools is actually included in the dependency tree of px-layout-design already. After running a `bower install` it should have been found without an error within your bower_components folder.
