### ISSUE TITLE
This stylesheet gives compilation errors

### ISSUE THREAD

**Issue by binson1989** [PredixDev/px-layout-design#4]
- It seems to refer inuit-responsive-tools which doesn't get installed as its dependency.
- It is using a media-query named 'desk-wide' which I am not able to find anywhere, even after installing inuit-responsive-tools separately.

Is this the right package to refer to to design layout of predix apps?

**Comment by randyaskin** [comment]
The bower.json dependencies were fixed a while ago, but I've updated the breakpoint with the correct name (desk, not desk-wide) which comes from inuit-responsive-settings. See v0.4.2.
