### ISSUE TITLE
Add auto sizing explanation to demo

### ISSUE THREAD

**Issue by katemenkhaus** [PredixDev/px-layout-design#5]
Add explanation/demo of how the grid works
![screen shot 2017-03-02 at 4 08 02 pm](https://cloud.githubusercontent.com/assets/14931112/23533717/46e5cdba-ff68-11e6-88a7-86498afd1936.png)

Add explanation/demo of how the auto sizing works with percentage-base sizing  
![screen shot 2017-03-02 at 4 08 08 pm](https://cloud.githubusercontent.com/assets/14931112/23533727/4987f55c-ff68-11e6-8b05-0c46904c0410.png)

**Comment by randyaskin** [comment]
Added in v0.4.6.
